### ISSUE TITLE
PROPOSAL: Simplify git branching structure

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2003]
### Background Information

The R community has a typical branching structure used among the vast majority of open source package projects.  I propose we update to follow the community structure. The community uses the main branch for the latest dev version of the package. I think we recently saw this when Hadley tried to make an update to the repo, but couldn't find the correct place to make the change.

### Definition of Done

- [ ] make main the default branch
- [ ] remove the devel branch
- [ ] clean up stale branches

**Comment by bms63** [comment]
im just wondering what would be impacted by dropping the `devel` branches from `admiral`, `admiraldev` and `admiral.test/admiraldata`

I think pretty minimal??

* Impact to staged.dependencies process
* Guidance on how to patch a bug and re-release
* Website deployment with github release/tag
* others?

**Comment by bundfussr** [comment]
> https://bookdown.netlify.app/hadley/r-pkgs/release.html (also https://r-pkgs.org/release.html for a cleaner interface) is what the R community uses. Semver 2.0 is the gold standard, however.

I couldn't find anything regarding branches.

How would you do a hotfix? Create a hotfix branch from the last release tag, do the fixes there, submit from the hotfix branch, update the website from the hotfix branch, do a release from the hotfix branch, and merge it back to main?

**Comment by bundfussr** [comment]
But if we create a new release from main, it may contain changes we do not want to release. For example, assume we have released 0.12.0, then we add some changes for 0.13.0 to main, and then we need a hotfix for 0.12.0. Version 0.12.1 should contain the updates for the hotfix but not the updates for 0.13.0.

And how would staged dependencies determine the correct version of the dependencies? For example, the workflows running for the hotfix should use the latest released version of the dependency and not main.

**Comment by ddsjoberg** [comment]
That's a good point @cicdguy !

Regarding hotfixes in general: If we are ever in need of an immediate patch, the vast majority of the time we can make the fix and also release it along with any new features/fixes in main without any need for a hotfix branch

**Comment by bundfussr** [comment]
> Regarding hotfixes in general: If we are ever in need of an immediate patch, the vast majority of the time we can make the fix and also release it along with any new features/fixes in main without any need for a hotfix branch

I don't think that this works in our case. If we release everything in `main` together with the hotfix, we may deprecate functions or arguments earlier than announced before.  The changes in `main` could also affect other packages. For example, a change in admiral could require a change in admiraldev, i.e., admiraldev would need to be released as well. Or the change in admiral requires changes in admiral extension packages like admiralonco or admiralroche. These may not be implemented when the hotfix should be released.

Therefore I would keep the hotfix changes and the changes for next scheduled release separate.

**Comment by ddsjoberg** [comment]
- @bundfussr you're raising good points about some edge cases we should be aware of. 
- I still maintain that in _most_ cases a "hotfix" is not needed as we could simply release everything in main if we needed to make an immediate/unexpected release
- I also suspect the need for unexpected and immediate releases will continue to decrease: the package is so well-maintained and the unit testing coverage is amazing.
- @cicdguy If we make a tagged release from a branch and the branch is later deleted, the tag will persist. (I recall searching this up a few years ago, and a quick search found some posts confirming. I would test this before updating the branching scheme.)

**Comment by ddsjoberg** [comment]
Good point, I am however fine with this message, since the snapshot of the repo still exists and I would imagine the frequency of having the old hotfix release tag checked out is pretty minimal

**Comment by bms63** [comment]
@cicdguy is going to demo proposal at next CI meeting.  @ddsjoberg i will forward invite.

**Comment by bms63** [comment]
@cicdguy are you still good for Tuesday July 25th demo of how we should starting using this simplified git branching structure?

I think our biggest concern was patching/hotfixing.

**Comment by bms63** [comment]
@cicdguy What about August 8th IDR meeting or we could just have a one-off meeting around this topic.

**Comment by bundfussr** [comment]
> @cicdguy What about August 8th IDR meeting or we could just have a one-off meeting around this topic.

I am on vacation in that week.

**Comment by bms63** [comment]
@ddsjoberg do you mind guiding us into this new glory?  Perhaps we can iron out any misgivings or trepidations on Wednesday?  It would be nice to figure this out before we get closer to a release - just in past history of admiral when we do CI updates/updates to processes it tends to cause us some headaches if we do it close to a release.

**Comment by ddsjoberg** [comment]
@bms63 yes, of course!

**Comment by ddsjoberg** [comment]
It seems from our chats, there is caution for hotfixes that require an immediate release to CRAN when there are other items in main that, for whatever reason, cannot be included in the ahead-of-schedule release. I think we can iron out those details in a straight-forward way. If there other concerns, please let me know ahead of Wed if you can!

**Comment by ddsjoberg** [comment]
@cicdguy and @ddsjoberg met to discuss the details of the GitHub Flow update. We will aim to make this change to GitHub Flow after the next admiral release in Sept. The following items will need to be addressed/completed.

- [ ] change the default branch back to main, and retire the branches that are no longer needed (e.g. devel)
- [ ] we will now be using dev version numbering in DESCRIPTION. Update the PR ISSUE TEMPLATE with instructions on incrementing the version number with `usethis::use_version(which='dev')`, and updating the `NEWS.md` file under the heading `# admiral (development version)`. The version numbers in DESCRIPTION and the version numbers in header of `NEWS.md` are auto-updated with `usethis::use_version()`.
- [ ] we can now use the standard pkgdown yaml to create the website for the latest release and dev versions (two separate websites) with the latest release in the root of the gh-pages branch and the latest dev site in the 'dev' folder (pkgdown default) 
    - [ ] update `pkgdown.yml` with dev mode activated (which adds the dev site to the `dev` folder on gh-pages)
    - [ ] update links in the "versions" drop down to point to the correct versions. the main, cran-release links will be updated to point to the root.
    - [ ] there are existing sites that will no longer be updated/used: cran-release, devel, latest-tag, main, patch, pre-release. Each of the sites in these gh-pages folders should probably be replaced with a single `index.html` file that redirects the users to the appropriate page (mostly to the root/main page).
- [ ] update the dev guide(s) with information on the GitHub Flow structure

**Comment by bms63** [comment]
Hi @ddsjoberg - will you be taking this on after September release or do you want someone else to do it?

**Comment by ddsjoberg** [comment]
@bms63 I can do most of it, but will need someone with more permissions to change default branch, for example. 

When the time comes, I can create a separate issue for each step to keep better track of convos surrounding specific tasks. For example, we have websites in folders `main`, `cran-release`, etc. Above I recommended placing an `index.html` in the folders to redirect users to the main site. But this weekend, I was thinking about how links to specific help pages would then break. For example, this page on `cran-release` would no longer exist: https://pharmaverse.github.io/admiral/cran-release/reference/derive_var_extreme_flag.html . Is there a way to easily add redirects for all these pages to the main page? @cicdguy ? I think there may be a way to include information in a `404.html` file, or even make that a redirect itself?

**Comment by bms63** [comment]
Something to keep track of/update `URL:` ????
![image](https://github.com/pharmaverse/admiral/assets/10111024/091478e8-cda4-404f-b471-a9b09813f878)

**Comment by ddsjoberg** [comment]
@bms63 for the next release we can keep the website folder structure as it is now in `gh-pages`. But we can additionally add a version of the release website to the root directory, which will match the location listed in our DESCRIPTION file.

This has the added benefit of allowing us to seamlessly update the folder structure in `gh-pages` while the primary/release website remains in root unchanged and always available to users.

**Comment by bms63** [comment]
@ddsjoberg I made you an admin so you can get started on this - let me know if you need any help

**Comment by bms63** [comment]
#2104 I believe this issue captures the actions needed to complete the simplification of our git branching strategy.  I will link this issue with it, but closing as seems redundant.
